// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksmxyvahwbzklekamqje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbXh5dmFod2J6a2xla2FtcWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjE5NTMsImV4cCI6MjA1Nzk5Nzk1M30.Zl2tH5S1d3HJYPFba0whkihm8mqGb1HHdZmoXs9sz7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);