// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://sbisllattwisnaxapphc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiaXNsbGF0dHdpc25heGFwcGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODgwODQsImV4cCI6MjA1OTE2NDA4NH0.Lj-HU_UPmeS6MxvK6SUxs4O1TxoV8g79pjngqx67YfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
