// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vadugrtrkloholumdrum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZHVncnRya2xvaG9sdW1kcnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTA0ODMsImV4cCI6MjA1ODA4NjQ4M30.VvKgQ2BKMcrNr2oo-rI2iRHXH0yOW6xsVcuM1oVjDrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
